title: Lin's Essays
description: Thoughts and essays.
author: Lin
lang: en

theme: jekyll-theme-architect

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      type: posts
    values:
      layout: default

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
